# Generated by Django 3.1.2 on 2020-11-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_extinguish', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FireExtinguisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('last_inspection', models.DateTimeField(auto_now_add=True)),
                ('upcoming_inspection', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Building',
        ),
    ]
