# Generated by Django 3.1.2 on 2020-11-05 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_extinguish', '0002_auto_20201103_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='FEInspectionForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_tested', models.DateTimeField(auto_now_add=True)),
                ('tester', models.CharField(max_length=100)),
                ('ionization_test', models.CharField(max_length=100)),
                ('heat_detector_test', models.CharField(max_length=100)),
                ('manual_pull_station_test', models.CharField(max_length=100)),
                ('lamp_test', models.CharField(max_length=100)),
            ],
        ),
    ]
