# Generated by Django 3.1.2 on 2020-11-14 23:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fire_extinguish', '0004_auto_20201105_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fireextinguisher',
            name='last_inspection',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='fireextinguisher',
            name='upcoming_inspection',
            field=models.DateTimeField(blank=True),
        ),
    ]
