# Generated by Django 3.1.2 on 2020-11-18 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire_extinguish', '0007_auto_20201114_1758'),
    ]

    operations = [
    ]
