# Generated by Django 3.1.2 on 2020-11-19 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fire_extinguish', '0012_auto_20201118_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fireextinguisher',
            name='last_inspection',
        ),
        migrations.RemoveField(
            model_name='fireextinguisher',
            name='upcoming_inspection',
        ),
        migrations.RemoveField(
            model_name='fireextinguisher',
            name='code',
        ),
        migrations.AddField(
            model_name='fireextinguisher',
            name='last_12year_test',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fireextinguisher',
            name='last_6year_service',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fireextinguisher',
            name='number',
            field=models.DateTimeField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='fireextinguisher',
            name='last_annual_inspection',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fireextinguisher',
            name='last_monthly_inspection',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fireextinguisher',
            name='upcoming_12year_test',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fireextinguisher',
            name='upcoming_6year_service',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fireextinguisher',
            name='upcoming_annual_inspection',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fireextinguisher',
            name='upcoming_monthly_inspection',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
