# Generated by Django 3.1.2 on 2020-11-21 03:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fire_extinguish', '0015_auto_20201120_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feinspection',
            name='date_tested',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
