# Generated by Django 3.1.2 on 2020-11-24 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fire_extinguish', '0016_auto_20201120_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='FENotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=240)),
                ('fire_extinguisher', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='fire_extinguisher', to='fire_extinguish.fireextinguisher')),
            ],
        ),
    ]
