# Generated by Django 3.1.2 on 2020-11-28 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire_extinguish', '0017_auto_20201123_2200'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Building',
        # ),
    ]
