# Generated by Django 3.1.2 on 2020-11-28 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire_extinguish', '0019_delete_building'),
    ]

    operations = [
        # migrations.DeleteModel(
        #     name='Building',
        # ),
    ]
