# Generated by Django 3.1.2 on 2020-12-04 07:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0002_auto_20201118_1353'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirePump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_monthly_inspection', models.DateTimeField(default=django.utils.timezone.now)),
                ('upcoming_monthly_inspection', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_annual_inspection', models.DateTimeField(default=django.utils.timezone.now)),
                ('upcoming_annual_inspection', models.DateTimeField(default=django.utils.timezone.now)),
                ('building', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='buildingsss', to='buildings.building')),
            ],
        ),
        migrations.CreateModel(
            name='PumpNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=240)),
                ('fire_pump', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='fpump', to='pumps.firepump')),
            ],
        ),
        migrations.CreateModel(
            name='PumpInspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suction_pressure', models.CharField(max_length=100)),
                ('discharge_pressure', models.CharField(max_length=100)),
                ('run_time', models.CharField(max_length=100)),
                ('inspection_type', models.CharField(max_length=100)),
                ('date_tested', models.DateTimeField(default=django.utils.timezone.now)),
                ('tester', models.CharField(max_length=100)),
                ('fire_pump', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='pump', to='pumps.firepump')),
            ],
        ),
    ]
