# Generated by Django 3.1.2 on 2020-11-28 23:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_auto_20201118_1353'),
        ('sprinklers', '0002_sprinklerinspectionform'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprinklerSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_type', models.CharField(max_length=100)),
                ('last_weekly_inspection', models.DateTimeField(default=django.utils.timezone.now)),
                ('upcoming_weekly_inspection', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_monthly_inspection', models.DateTimeField(default=django.utils.timezone.now)),
                ('upcoming_monthly_inspection', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_quarterly_inspection', models.DateTimeField(default=django.utils.timezone.now)),
                ('upcoming_quarterly_inspection', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_semiannual_inspection', models.DateTimeField(default=django.utils.timezone.now)),
                ('upcoming_semiannual_inspection', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_annual_inspection', models.DateTimeField(default=django.utils.timezone.now)),
                ('upcoming_annual_inspection', models.DateTimeField(default=django.utils.timezone.now)),
                ('building', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='buildingS', to='buildings.building')),
            ],
        ),
        migrations.CreateModel(
            name='SprinklerSystemInspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_pressure', models.CharField(max_length=25)),
                ('water_pressure', models.CharField(max_length=25)),
                ('inspection_type', models.CharField(max_length=100)),
                ('date_tested', models.DateTimeField(default=django.utils.timezone.now)),
                ('tester', models.CharField(max_length=100)),
                ('sprinkler_system', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sprinkler_sys', to='sprinklers.sprinklersystem')),
            ],
        ),
        migrations.CreateModel(
            name='SprinklerSystemNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=240)),
                ('sprinkler_system', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='sprinkler_system', to='sprinklers.sprinklersystem')),
            ],
        ),
        migrations.DeleteModel(
            name='SprinklerInspectionForm',
        ),
        migrations.DeleteModel(
            name='Sprinklers',
        ),
    ]
