# Generated by Django 3.1.2 on 2020-12-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprinklers', '0003_auto_20201128_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprinklersystem',
            name='coverage',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
