# Generated by Django 3.1.2 on 2020-11-18 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='code',
        ),
        migrations.RemoveField(
            model_name='building',
            name='last_inspection',
        ),
    ]
