# Generated by Django 3.1.2 on 2020-11-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmInspectionForm',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date_tested', models.DateTimeField(auto_now_add=True)),
                ('tester', models.CharField(max_length=100)),
                ('sound_test', models.CharField(max_length=100)),
            ],
        ),
    ]
