# Generated by Django 3.1.2 on 2020-11-28 18:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_auto_20201118_1353'),
        ('alarms', '0002_alarminspectionform'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_monthly_inspection', models.DateTimeField(default=django.utils.timezone.now)),
                ('upcoming_monthly_inspection', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_semiannual_inspection', models.DateTimeField(default=django.utils.timezone.now)),
                ('upcoming_semiannual_inspection', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_annual_inspection', models.DateTimeField(default=django.utils.timezone.now)),
                ('upcoming_annual_inspection', models.DateTimeField(default=django.utils.timezone.now)),
                ('building', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='building', to='buildings.building')),
            ],
        ),
        migrations.CreateModel(
            name='AlarmSystemInspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(max_length=100)),
                ('date_tested', models.DateTimeField(default=django.utils.timezone.now)),
                ('tester', models.CharField(max_length=100)),
                ('alarm_system', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='alarm_sys', to='alarms.alarmsystem')),
            ],
        ),
        migrations.CreateModel(
            name='AlarmSystemNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=240)),
                ('fire_extinguisher', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='alarm_system', to='alarms.alarmsystem')),
            ],
        ),
        migrations.DeleteModel(
            name='AlarmInspectionForm',
        ),
        migrations.DeleteModel(
            name='Alarms',
        ),
    ]
