# Generated by Django 3.1.2 on 2020-11-28 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alarms', '0003_auto_20201128_1217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarmsystemnotes',
            old_name='fire_extinguisher',
            new_name='alarm_system',
        ),
    ]
